// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABHEPEDZv-q-ydq-ajkxTLZqNtcTxcFBU',
    appId: '1:785084987947:web:c54e5a43f33f8fe2c1886e',
    messagingSenderId: '785084987947',
    projectId: 'nudge-fit-7f983',
    authDomain: 'nudge-fit-7f983.firebaseapp.com',
    storageBucket: 'nudge-fit-7f983.firebasestorage.app',
    measurementId: 'G-SX2LS6VFG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMKIVs4M1p2GIBPeHGQ2KT0mS7nLDSNn0',
    appId: '1:785084987947:android:840fb645d202227dc1886e',
    messagingSenderId: '785084987947',
    projectId: 'nudge-fit-7f983',
    storageBucket: 'nudge-fit-7f983.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwNhW9iokOrCeC7wZX2sIEElHQTnUA4kM',
    appId: '1:785084987947:ios:da39b44eff892613c1886e',
    messagingSenderId: '785084987947',
    projectId: 'nudge-fit-7f983',
    storageBucket: 'nudge-fit-7f983.firebasestorage.app',
    iosBundleId: 'com.salimer.nudgeFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwNhW9iokOrCeC7wZX2sIEElHQTnUA4kM',
    appId: '1:785084987947:ios:bfc8b182fe04699fc1886e',
    messagingSenderId: '785084987947',
    projectId: 'nudge-fit-7f983',
    storageBucket: 'nudge-fit-7f983.firebasestorage.app',
    iosBundleId: 'com.example.nudgeFitFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABHEPEDZv-q-ydq-ajkxTLZqNtcTxcFBU',
    appId: '1:785084987947:web:d6feb0dd55d485bec1886e',
    messagingSenderId: '785084987947',
    projectId: 'nudge-fit-7f983',
    authDomain: 'nudge-fit-7f983.firebaseapp.com',
    storageBucket: 'nudge-fit-7f983.firebasestorage.app',
    measurementId: 'G-MJH48SY8NC',
  );
}
